PipeWire: pw_module Class Reference
pw_module Class Reference
A dynamically loadable module.
Public Types
typedef bool(* pw_module_init_func_t) (struct pw_module *module, char *args)
Module init function signature.
Public Member Functions
struct pw_module * pw_module_load (struct pw_core *core, const char *name, const char *args)
Load a module.
void pw_module_destroy (struct pw_module *module)
Destroy a module.
Detailed Description
A dynamically loadable module.
Member Typedef Documentation
pw_module_init_func_t
typedef bool(* pw_module_init_func_t) (struct pw_module *module, char *args)
Module init function signature.
Parameters
module A pw_module
args Arguments to the module
Returns
true on success, false otherwise
A module should provide an init function with this signature. This function will be called when a module is loaded.
Member Function Documentation
pw_module_destroy()
void pw_module_destroy (struct pw_module * module)
Destroy a module.
Parameters
module the module to destroy
References pw_global_destroy(), and pw_resource_destroy().
pw_module_load()
struct pw_module * pw_module_load (struct pw_core * core, const char * name, const char * args)
Load a module.
Parameters
core a pw_core
name name of the module to load
args A string with arguments for the module
[out] error Return location for an error string, or NULL
Returns
A pw_module if the module could be loaded, or NULL on failure.
References pw_split_strv().
The documentation for this class was generated from the following files:
module.h
module.c