PipeWire: introspect.c File Reference
introspect.c File Reference
Functions
const char * pw_node_state_as_string (enum pw_node_state state)
const char * pw_direction_as_string (enum pw_direction direction)
const char * pw_link_state_as_string (enum pw_link_state state)
struct pw_core_info * pw_core_info_update (struct pw_core_info *info, const struct pw_core_info *update)
void pw_core_info_free (struct pw_core_info *info)
struct pw_node_info * pw_node_info_update (struct pw_node_info *info, const struct pw_node_info *update)
void pw_node_info_free (struct pw_node_info *info)
struct pw_module_info * pw_module_info_update (struct pw_module_info *info, const struct pw_module_info *update)
void pw_module_info_free (struct pw_module_info *info)
struct pw_client_info * pw_client_info_update (struct pw_client_info *info, const struct pw_client_info *update)
void pw_client_info_free (struct pw_client_info *info)
struct pw_link_info * pw_link_info_update (struct pw_link_info *info, const struct pw_link_info *update)
void pw_link_info_free (struct pw_link_info *info)
Function Documentation
pw_client_info_free()
void pw_client_info_free (struct pw_client_info * info)
References pw_client_info::props.
pw_client_info_update()
struct pw_client_info* pw_client_info_update (struct pw_client_info * info, const struct pw_client_info * update)
References pw_client_info::change_mask, pw_client_info::props, and PW_CLIENT_CHANGE_MASK_PROPS.
pw_core_info_free()
void pw_core_info_free (struct pw_core_info * info)
References pw_core_info::host_name, pw_core_info::name, pw_core_info::props, pw_core_info::user_name, and pw_core_info::version.
Referenced by pw_remote_disconnect().
pw_core_info_update()
struct pw_core_info* pw_core_info_update (struct pw_core_info * info, const struct pw_core_info * update)
References pw_core_info::change_mask, pw_core_info::cookie, pw_core_info::host_name, pw_core_info::name, pw_core_info::props, PW_CORE_CHANGE_MASK_COOKIE, PW_CORE_CHANGE_MASK_HOST_NAME, PW_CORE_CHANGE_MASK_NAME, PW_CORE_CHANGE_MASK_PROPS, PW_CORE_CHANGE_MASK_USER_NAME, PW_CORE_CHANGE_MASK_VERSION, pw_core_info::user_name, and pw_core_info::version.
pw_direction_as_string()
const char* pw_direction_as_string (enum pw_direction direction)
References PW_DIRECTION_INPUT, and PW_DIRECTION_OUTPUT.
pw_link_info_free()
void pw_link_info_free (struct pw_link_info * info)
References pw_link_info::format.
pw_link_info_update()
struct pw_link_info* pw_link_info_update (struct pw_link_info * info, const struct pw_link_info * update)
References pw_link_info::change_mask, pw_link_info::format, pw_link_info::input_node_id, pw_link_info::input_port_id, pw_link_info::output_node_id, pw_link_info::output_port_id, PW_LINK_CHANGE_MASK_FORMAT, PW_LINK_CHANGE_MASK_INPUT, PW_LINK_CHANGE_MASK_OUTPUT, and spa_format_copy.
pw_link_state_as_string()
const char* pw_link_state_as_string (enum pw_link_state state)
References PW_LINK_STATE_ALLOCATING, PW_LINK_STATE_ERROR, PW_LINK_STATE_INIT, PW_LINK_STATE_NEGOTIATING, PW_LINK_STATE_PAUSED, PW_LINK_STATE_RUNNING, and PW_LINK_STATE_UNLINKED.
pw_module_info_free()
void pw_module_info_free (struct pw_module_info * info)
References pw_module_info::args, pw_module_info::filename, pw_module_info::name, and pw_module_info::props.
pw_module_info_update()
struct pw_module_info* pw_module_info_update (struct pw_module_info * info, const struct pw_module_info * update)
References pw_module_info::args, pw_module_info::change_mask, pw_module_info::filename, pw_module_info::name, pw_module_info::props, PW_MODULE_CHANGE_MASK_ARGS, PW_MODULE_CHANGE_MASK_FILENAME, PW_MODULE_CHANGE_MASK_NAME, and PW_MODULE_CHANGE_MASK_PROPS.
pw_node_info_free()
void pw_node_info_free (struct pw_node_info * info)
References pw_node_info::error, pw_node_info::input_formats, pw_node_info::n_input_formats, pw_node_info::n_output_formats, pw_node_info::name, pw_node_info::output_formats, and pw_node_info::props.
pw_node_info_update()
struct pw_node_info* pw_node_info_update (struct pw_node_info * info, const struct pw_node_info * update)
References pw_node_info::change_mask, pw_node_info::error, pw_node_info::input_formats, pw_node_info::max_input_ports, pw_node_info::max_output_ports, pw_node_info::n_input_formats, pw_node_info::n_input_ports, pw_node_info::n_output_formats, pw_node_info::n_output_ports, pw_node_info::name, pw_node_info::output_formats, pw_node_info::props, PW_NODE_CHANGE_MASK_INPUT_FORMATS, PW_NODE_CHANGE_MASK_INPUT_PORTS, PW_NODE_CHANGE_MASK_NAME, PW_NODE_CHANGE_MASK_OUTPUT_FORMATS, PW_NODE_CHANGE_MASK_OUTPUT_PORTS, PW_NODE_CHANGE_MASK_PROPS, PW_NODE_CHANGE_MASK_STATE, spa_format_copy, and pw_node_info::state.
pw_node_state_as_string()
const char* pw_node_state_as_string (enum pw_node_state state)
References PW_NODE_STATE_CREATING, PW_NODE_STATE_ERROR, PW_NODE_STATE_IDLE, PW_NODE_STATE_RUNNING, and PW_NODE_STATE_SUSPENDED.
Referenced by pw_node::pw_node_set_state(), and pw_node::pw_node_update_state().