PipeWire: link.c File Reference
link.c File Reference
Macros
#define MAX_BUFFERS 16
Functions
bool pw_link_activate (struct pw_link *this)
bool pw_link_deactivate (struct pw_link *this)
struct pw_link * pw_link_new (struct pw_core *core, struct pw_global *parent, struct pw_port *output, struct pw_port *input, struct spa_format *format_filter, struct pw_properties *properties, char **error, size_t user_data_size)
void pw_link_destroy (struct pw_link *link)
void pw_link_add_listener (struct pw_link *link, struct spa_hook *listener, const struct pw_link_events *events, void *data)
Add an event listener to link.
struct pw_link * pw_link_find (struct pw_port *output_port, struct pw_port *input_port)
struct pw_core * pw_link_get_core (struct pw_link *link)
Get the core of a link.
void * pw_link_get_user_data (struct pw_link *link)
Get the user_data of a link, the size of the memory is given when constructing the link.
const struct pw_link_info * pw_link_get_info (struct pw_link *link)
Get the link info.
struct pw_global * pw_link_get_global (struct pw_link *link)
Get the global of the link.
struct pw_port * pw_link_get_output (struct pw_link *link)
Get the output port of the link.
struct pw_port * pw_link_get_input (struct pw_link *link)
Get the input port of the link.
void pw_link_inc_idle (struct pw_link *link)
Indicate that linked nodes can be idle even when linked with this link.
Macro Definition Documentation
MAX_BUFFERS
#define MAX_BUFFERS 16
Function Documentation
pw_link_activate()
bool pw_link_activate (struct pw_link * this)
References pw_work_queue_add().
pw_link_add_listener()
void pw_link_add_listener (struct pw_link * link, struct spa_hook * listener, const struct pw_link_events * events, void * data)
Add an event listener to link.
pw_link_deactivate()
bool pw_link_deactivate (struct pw_link * this)
References pw_loop_invoke.
Referenced by pw_link_destroy().
pw_link_destroy()
void pw_link_destroy (struct pw_link * link)
References pw_global_destroy(), pw_link_deactivate(), and pw_resource_destroy().
pw_link_find()
struct pw_link* pw_link_find (struct pw_port * output_port, struct pw_port * input_port)
Referenced by pw_link_new().
pw_link_get_core()
struct pw_core* pw_link_get_core (struct pw_link * link)
Get the core of a link.
pw_link_get_global()
struct pw_global* pw_link_get_global (struct pw_link * link)
Get the global of the link.
pw_link_get_info()
const struct pw_link_info* pw_link_get_info (struct pw_link * link)
Get the link info.
pw_link_get_input()
struct pw_port* pw_link_get_input (struct pw_link * link)
Get the input port of the link.
pw_link_get_output()
struct pw_port* pw_link_get_output (struct pw_link * link)
Get the output port of the link.
pw_link_get_user_data()
void* pw_link_get_user_data (struct pw_link * link)
Get the user_data of a link, the size of the memory is given when constructing the link.
pw_link_inc_idle()
void pw_link_inc_idle (struct pw_link * link)
Indicate that linked nodes can be idle even when linked with this link.
pw_link_new()
struct pw_link* pw_link_new (struct pw_core * core, struct pw_global * parent, struct pw_port * output, struct pw_port * input, struct spa_format * format_filter, struct pw_properties * properties, char ** error, size_t user_data_size)
References pw_properties::dict, PW_DIRECTION_INPUT, PW_DIRECTION_OUTPUT, pw_link_find(), PW_LINK_STATE_INIT, pw_loop_invoke, pw_node_add_listener(), pw_port_add_listener(), and pw_work_queue_new().