PipeWire: node.c File Reference
node.c File Reference
Functions
void pw_node_register (struct pw_node *this)
Complete initialization of the node and register.
struct pw_node * pw_node_new (struct pw_core *core, struct pw_resource *owner, struct pw_global *parent, const char *name, struct pw_properties *properties, size_t user_data_size)
const struct pw_node_info * pw_node_get_info (struct pw_node *node)
Get the node info.
void * pw_node_get_user_data (struct pw_node *node)
Get node user_data.
struct pw_core * pw_node_get_core (struct pw_node *node)
Get the core of this node.
struct pw_resource * pw_node_get_owner (struct pw_node *node)
Get the node owner or NULL when not owned by a remote client.
struct pw_global * pw_node_get_global (struct pw_node *node)
Get the global of this node.
const struct pw_properties * pw_node_get_properties (struct pw_node *node)
Get the node properties.
void pw_node_update_properties (struct pw_node *node, const struct spa_dict *dict)
Update the node properties.
void pw_node_set_implementation (struct pw_node *node, struct spa_node *spa_node)
Set the node implementation.
struct spa_node * pw_node_get_implementation (struct pw_node *node)
Get the node implementation.
void pw_node_add_listener (struct pw_node *node, struct spa_hook *listener, const struct pw_node_events *events, void *data)
Add an event listener.
void pw_node_set_max_ports (struct pw_node *node, uint32_t max_input_ports, uint32_t max_output_ports)
Configure the maximum input and output ports.
bool pw_node_for_each_port (struct pw_node *node, enum pw_direction direction, bool(*callback)(void *data, struct pw_port *port), void *data)
iterate the ports in the given direction
struct pw_port * pw_node_find_port (struct pw_node *node, enum pw_direction direction, uint32_t port_id)
Find the port with direction and port_id or NULL when not found.
uint32_t pw_node_get_free_port_id (struct pw_node *node, enum pw_direction direction)
Get a free unused port_id from the node.
Function Documentation
pw_node_add_listener()
void pw_node_add_listener (struct pw_node * node, struct spa_hook * listener, const struct pw_node_events * events, void * data)
Add an event listener.
Referenced by pw_link_new().
pw_node_find_port()
struct pw_port* pw_node_find_port (struct pw_node * node, enum pw_direction direction, uint32_t port_id)
Find the port with direction and port_id or NULL when not found.
References PW_DIRECTION_INPUT, and pw_map::pw_map_lookup().
pw_node_for_each_port()
bool pw_node_for_each_port (struct pw_node * node, enum pw_direction direction, bool(*)(void *data, struct pw_port *port) callback, void * data)
iterate the ports in the given direction
References PW_DIRECTION_INPUT.
pw_node_get_core()
struct pw_core* pw_node_get_core (struct pw_node * node)
Get the core of this node.
pw_node_get_free_port_id()
uint32_t pw_node_get_free_port_id (struct pw_node * node, enum pw_direction direction)
Get a free unused port_id from the node.
References PW_DIRECTION_INPUT, and pw_map::pw_map_insert_new().
pw_node_get_global()
struct pw_global* pw_node_get_global (struct pw_node * node)
Get the global of this node.
pw_node_get_implementation()
struct spa_node* pw_node_get_implementation (struct pw_node * node)
Get the node implementation.
pw_node_get_info()
const struct pw_node_info* pw_node_get_info (struct pw_node * node)
Get the node info.
pw_node_get_owner()
struct pw_resource* pw_node_get_owner (struct pw_node * node)
Get the node owner or NULL when not owned by a remote client.
pw_node_get_properties()
const struct pw_properties* pw_node_get_properties (struct pw_node * node)
Get the node properties.
pw_node_get_user_data()
void* pw_node_get_user_data (struct pw_node * node)
Get node user_data.
The size of the memory was given in pw_node_new
pw_node_new()
struct pw_node* pw_node_new (struct pw_core * core, struct pw_resource * owner, struct pw_global * parent, const char * name, struct pw_properties * properties, size_t user_data_size)
References pw_properties::dict, PW_NODE_STATE_CREATING, pw_properties_new(), and pw_work_queue_new().
pw_node_register()
void pw_node_register (struct pw_node * this)
Complete initialization of the node and register.
pw_node_set_implementation()
void pw_node_set_implementation (struct pw_node * node, struct spa_node * spa_node)
Set the node implementation.
pw_node_set_max_ports()
void pw_node_set_max_ports (struct pw_node * node, uint32_t max_input_ports, uint32_t max_output_ports)
Configure the maximum input and output ports.
References PW_NODE_CHANGE_MASK_INPUT_PORTS, and PW_NODE_CHANGE_MASK_OUTPUT_PORTS.
pw_node_update_properties()
void pw_node_update_properties (struct pw_node * node, const struct spa_dict * dict)
Update the node properties.
References PW_NODE_CHANGE_MASK_PROPS, pw_node_resource_info, and pw_properties_set().