PipeWire: node-factory.c File Reference
node-factory.c File Reference
Functions
struct pw_node_factory * pw_node_factory_new (struct pw_core *core, const char *name, size_t user_data_size)
void pw_node_factory_destroy (struct pw_node_factory *factory)
void pw_node_factory_export (struct pw_node_factory *factory, struct pw_client *owner, struct pw_global *parent)
void * pw_node_factory_get_user_data (struct pw_node_factory *factory)
void pw_node_factory_set_implementation (struct pw_node_factory *factory, const struct pw_node_factory_implementation *implementation, void *data)
struct pw_node * pw_node_factory_create_node (struct pw_node_factory *factory, struct pw_resource *resource, const char *name, struct pw_properties *properties)
Function Documentation
pw_node_factory_create_node()
struct pw_node* pw_node_factory_create_node (struct pw_node_factory * factory, struct pw_resource * resource, const char * name, struct pw_properties * properties)
pw_node_factory_destroy()
void pw_node_factory_destroy (struct pw_node_factory * factory)
References pw_global::pw_global_destroy(), and pw_log::pw_log_debug().
pw_node_factory_export()
void pw_node_factory_export (struct pw_node_factory * factory, struct pw_client * owner, struct pw_global * parent)
References pw_core::pw_core_add_global().
pw_node_factory_get_user_data()
void* pw_node_factory_get_user_data (struct pw_node_factory * factory)
pw_node_factory_new()
struct pw_node_factory* pw_node_factory_new (struct pw_core * core, const char * name, size_t user_data_size)
References pw_log::pw_log_debug().
pw_node_factory_set_implementation()
void pw_node_factory_set_implementation (struct pw_node_factory * factory, const struct pw_node_factory_implementation * implementation, void * data)