PipeWire: node.h File Reference
node.h File Reference
Data Structures
struct pw_node_events
Node events, listen to them with pw_node_add_listener.
Macros
#define PW_TYPE__Node PW_TYPE_OBJECT_BASE "Node"
#define PW_TYPE_NODE_BASE PW_TYPE__Node ":"
#define PW_VERSION_NODE_EVENTS 0
Functions
void pw_node_register (struct pw_node *node)
Complete initialization of the node and register.
void pw_node_destroy (struct pw_node *node)
Destroy a node.
void pw_node_set_max_ports (struct pw_node *node, uint32_t max_input_ports, uint32_t max_output_ports)
Configure the maximum input and output ports.
const struct pw_node_info * pw_node_get_info (struct pw_node *node)
Get the node info.
void * pw_node_get_user_data (struct pw_node *node)
Get node user_data.
struct pw_core * pw_node_get_core (struct pw_node *node)
Get the core of this node.
struct pw_resource * pw_node_get_owner (struct pw_node *node)
Get the node owner or NULL when not owned by a remote client.
struct pw_global * pw_node_get_global (struct pw_node *node)
Get the global of this node.
const struct pw_properties * pw_node_get_properties (struct pw_node *node)
Get the node properties.
void pw_node_update_properties (struct pw_node *node, const struct spa_dict *dict)
Update the node properties.
void pw_node_set_implementation (struct pw_node *node, struct spa_node *spa_node)
Set the node implementation.
struct spa_node * pw_node_get_implementation (struct pw_node *node)
Get the node implementation.
void pw_node_add_listener (struct pw_node *node, struct spa_hook *listener, const struct pw_node_events *events, void *data)
Add an event listener.
bool pw_node_for_each_port (struct pw_node *node, enum pw_direction direction, bool(*callback)(void *data, struct pw_port *port), void *data)
iterate the ports in the given direction
struct pw_port * pw_node_find_port (struct pw_node *node, enum pw_direction direction, uint32_t port_id)
Find the port with direction and port_id or NULL when not found.
uint32_t pw_node_get_free_port_id (struct pw_node *node, enum pw_direction direction)
Get a free unused port_id from the node.
struct pw_port * pw_node_get_free_port (struct pw_node *node, enum pw_direction direction)
Get a free unused port from the node, this can be an old unused existing port or a new port.
int pw_node_set_state (struct pw_node *node, enum pw_node_state state)
Change the state of the node.
void pw_node_update_state (struct pw_node *node, enum pw_node_state state, char *error)
Update the state of the node, mostly used by node implementations.
Macro Definition Documentation
PW_TYPE__Node
#define PW_TYPE__Node PW_TYPE_OBJECT_BASE "Node"
PW_TYPE_NODE_BASE
#define PW_TYPE_NODE_BASE PW_TYPE__Node ":"
PW_VERSION_NODE_EVENTS
#define PW_VERSION_NODE_EVENTS 0
Function Documentation
pw_node_add_listener()
void pw_node_add_listener (struct pw_node * node, struct spa_hook * listener, const struct pw_node_events * events, void * data)
Add an event listener.
Referenced by pw_link_new().
pw_node_destroy()
void pw_node_destroy (struct pw_node * node)
Destroy a node.
pw_node_find_port()
struct pw_port* pw_node_find_port (struct pw_node * node, enum pw_direction direction, uint32_t port_id)
Find the port with direction and port_id or NULL when not found.
References PW_DIRECTION_INPUT, and pw_map::pw_map_lookup().
pw_node_for_each_port()
bool pw_node_for_each_port (struct pw_node * node, enum pw_direction direction, bool(*)(void *data, struct pw_port *port) callback, void * data)
iterate the ports in the given direction
References PW_DIRECTION_INPUT.
pw_node_get_core()
struct pw_core* pw_node_get_core (struct pw_node * node)
Get the core of this node.
pw_node_get_free_port()
struct pw_port* pw_node_get_free_port (struct pw_node * node, enum pw_direction direction)
Get a free unused port from the node, this can be an old unused existing port or a new port.
Referenced by pw_core::pw_core_find_port().
pw_node_get_free_port_id()
uint32_t pw_node_get_free_port_id (struct pw_node * node, enum pw_direction direction)
Get a free unused port_id from the node.
References PW_DIRECTION_INPUT, and pw_map::pw_map_insert_new().
pw_node_get_global()
struct pw_global* pw_node_get_global (struct pw_node * node)
Get the global of this node.
pw_node_get_implementation()
struct spa_node* pw_node_get_implementation (struct pw_node * node)
Get the node implementation.
pw_node_get_info()
const struct pw_node_info* pw_node_get_info (struct pw_node * node)
Get the node info.
pw_node_get_owner()
struct pw_resource* pw_node_get_owner (struct pw_node * node)
Get the node owner or NULL when not owned by a remote client.
pw_node_get_properties()
const struct pw_properties* pw_node_get_properties (struct pw_node * node)
Get the node properties.
pw_node_get_user_data()
void* pw_node_get_user_data (struct pw_node * node)
Get node user_data.
The size of the memory was given in pw_node_new
pw_node_register()
void pw_node_register (struct pw_node * node)
Complete initialization of the node and register.
pw_node_set_implementation()
void pw_node_set_implementation (struct pw_node * node, struct spa_node * spa_node)
Set the node implementation.
pw_node_set_max_ports()
void pw_node_set_max_ports (struct pw_node * node, uint32_t max_input_ports, uint32_t max_output_ports)
Configure the maximum input and output ports.
References PW_NODE_CHANGE_MASK_INPUT_PORTS, and PW_NODE_CHANGE_MASK_OUTPUT_PORTS.
pw_node_set_state()
int pw_node_set_state (struct pw_node * node, enum pw_node_state state)
Change the state of the node.
pw_node_update_properties()
void pw_node_update_properties (struct pw_node * node, const struct spa_dict * dict)
Update the node properties.
References PW_NODE_CHANGE_MASK_PROPS, pw_node_resource_info, and pw_properties_set().
pw_node_update_state()
void pw_node_update_state (struct pw_node * node, enum pw_node_state state, char * error)
Update the state of the node, mostly used by node implementations.