PipeWire: node-factory.h File Reference
node-factory.h File Reference
Data Structures
struct pw_node_factory_implementation
Macros
#define PW_TYPE_INTERFACE__NodeFactory PW_TYPE_INTERFACE_BASE "NodeFactory"
#define PW_TYPE_NODE_FACTORY_BASE PW_TYPE_INTERFACE__NodeFactory ":"
#define PW_VERSION_NODE_FACRORY_IMPLEMENTATION 0
Functions
struct pw_node_factory * pw_node_factory_new (struct pw_core *core, const char *name, size_t user_data_size)
void pw_node_factory_export (struct pw_node_factory *factory, struct pw_client *owner, struct pw_global *parent)
void pw_node_factory_destroy (struct pw_node_factory *factory)
void * pw_node_factory_get_user_data (struct pw_node_factory *factory)
void pw_node_factory_set_implementation (struct pw_node_factory *factory, const struct pw_node_factory_implementation *implementation, void *data)
struct pw_node * pw_node_factory_create_node (struct pw_node_factory *factory, struct pw_resource *resource, const char *name, struct pw_properties *properties)
Macro Definition Documentation
PW_TYPE_INTERFACE__NodeFactory
#define PW_TYPE_INTERFACE__NodeFactory PW_TYPE_INTERFACE_BASE "NodeFactory"
Referenced by pw_type::pw_type_init().
PW_TYPE_NODE_FACTORY_BASE
#define PW_TYPE_NODE_FACTORY_BASE PW_TYPE_INTERFACE__NodeFactory ":"
PW_VERSION_NODE_FACRORY_IMPLEMENTATION
#define PW_VERSION_NODE_FACRORY_IMPLEMENTATION 0
Function Documentation
pw_node_factory_create_node()
struct pw_node* pw_node_factory_create_node (struct pw_node_factory * factory, struct pw_resource * resource, const char * name, struct pw_properties * properties)
pw_node_factory_destroy()
void pw_node_factory_destroy (struct pw_node_factory * factory)
References pw_global::pw_global_destroy(), and pw_log::pw_log_debug().
pw_node_factory_export()
void pw_node_factory_export (struct pw_node_factory * factory, struct pw_client * owner, struct pw_global * parent)
References pw_core::pw_core_add_global().
pw_node_factory_get_user_data()
void* pw_node_factory_get_user_data (struct pw_node_factory * factory)
pw_node_factory_new()
struct pw_node_factory* pw_node_factory_new (struct pw_core * core, const char * name, size_t user_data_size)
References pw_log::pw_log_debug().
pw_node_factory_set_implementation()
void pw_node_factory_set_implementation (struct pw_node_factory * factory, const struct pw_node_factory_implementation * implementation, void * data)