PipeWire: pipewire.c File Reference
pipewire.c File Reference
Data Structures
struct support_info
Functions
void * pw_get_support_interface (const char *type)
Get a support interface.
const struct spa_handle_factory * pw_get_support_factory (const char *factory_name)
const struct spa_support * pw_get_support (uint32_t *n_support)
Function Documentation
pw_get_support()
const struct spa_support* pw_get_support (uint32_t * n_support)
Referenced by pw_loop::pw_loop_new().
pw_get_support_factory()
const struct spa_handle_factory* pw_get_support_factory (const char * factory_name)
Referenced by pw_loop::pw_loop_new().
pw_get_support_interface()
void* pw_get_support_interface (const char * type)
Get a support interface.
Parameters
type the interface type
Returns
the interface or NULL when not configured
Referenced by pw_type::pw_type_init().