PipeWire: remote.c File Reference
remote.c File Reference
Functions
const char * pw_remote_state_as_string (enum pw_remote_state state)
void pw_remote_update_state (struct pw_remote *remote, enum pw_remote_state state, const char *fmt,...)
Update the state of the remote, mostly used by protocols.
struct pw_remote * pw_remote_new (struct pw_core *core, struct pw_properties *properties)
void pw_remote_destroy (struct pw_remote *remote)
struct pw_core * pw_remote_get_core (struct pw_remote *remote)
Get the core used to construct this remote.
enum pw_remote_state pw_remote_get_state (struct pw_remote *remote, const char **error)
Get the current state, error is set when state is PW_REMOTE_STATE_ERROR.
void pw_remote_add_listener (struct pw_remote *remote, struct spa_hook *listener, const struct pw_remote_events *events, void *data)
Add listener for events.
struct pw_core_proxy * pw_remote_get_core_proxy (struct pw_remote *remote)
Get the core proxy, can only be called when connected.
const struct pw_core_info * pw_remote_get_core_info (struct pw_remote *remote)
Get the remote core info, can only be called when connected.
struct pw_proxy * pw_remote_get_proxy (struct pw_remote *remote, uint32_t id)
Get the proxy with the given id.
int pw_remote_connect (struct pw_remote *remote)
int pw_remote_connect_fd (struct pw_remote *remote, int fd)
void pw_remote_disconnect (struct pw_remote *remote)
struct pw_proxy * pw_remote_export (struct pw_remote *remote, struct pw_node *node)
run a local node in a remote graph
Function Documentation
pw_remote_add_listener()
void pw_remote_add_listener (struct pw_remote * remote, struct spa_hook * listener, const struct pw_remote_events * events, void * data)
Add listener for events.
pw_remote_connect()
int pw_remote_connect (struct pw_remote * remote)
References pw_protocol_client_connect, PW_REMOTE_STATE_CONNECTING, PW_REMOTE_STATE_ERROR, and pw_remote_update_state().
pw_remote_connect_fd()
int pw_remote_connect_fd (struct pw_remote * remote, int fd)
References pw_protocol_client_connect_fd, PW_REMOTE_STATE_CONNECTING, PW_REMOTE_STATE_ERROR, and pw_remote_update_state().
pw_remote_destroy()
void pw_remote_destroy (struct pw_remote * remote)
References pw_properties_free(), pw_protocol_client_destroy, pw_remote_disconnect(), PW_REMOTE_STATE_UNCONNECTED, and pw_stream_destroy().
pw_remote_disconnect()
void pw_remote_disconnect (struct pw_remote * remote)
References pw_core_info_free(), pw_protocol_client_disconnect, pw_proxy_destroy(), PW_REMOTE_STATE_UNCONNECTED, pw_remote_update_state(), and pw_stream_disconnect().
Referenced by pw_remote_destroy().
pw_remote_export()
struct pw_proxy* pw_remote_export (struct pw_remote * remote, struct pw_node * node)
run a local node in a remote graph
pw_remote_get_core()
struct pw_core* pw_remote_get_core (struct pw_remote * remote)
Get the core used to construct this remote.
pw_remote_get_core_info()
const struct pw_core_info* pw_remote_get_core_info (struct pw_remote * remote)
Get the remote core info, can only be called when connected.
pw_remote_get_core_proxy()
struct pw_core_proxy* pw_remote_get_core_proxy (struct pw_remote * remote)
Get the core proxy, can only be called when connected.
pw_remote_get_proxy()
struct pw_proxy* pw_remote_get_proxy (struct pw_remote * remote, uint32_t id)
Get the proxy with the given id.
pw_remote_get_state()
enum pw_remote_state pw_remote_get_state (struct pw_remote * remote, const char ** error)
Get the current state, error is set when state is PW_REMOTE_STATE_ERROR.
pw_remote_new()
struct pw_remote* pw_remote_new (struct pw_core * core, struct pw_properties * properties)
References pw_core_find_protocol(), pw_fill_remote_properties(), pw_module_load(), pw_properties_free(), pw_properties_get(), pw_properties_new(), pw_protocol_new_client, and PW_REMOTE_STATE_UNCONNECTED.
pw_remote_state_as_string()
const char* pw_remote_state_as_string (enum pw_remote_state state)
References PW_REMOTE_STATE_CONNECTED, PW_REMOTE_STATE_CONNECTING, PW_REMOTE_STATE_ERROR, and PW_REMOTE_STATE_UNCONNECTED.
Referenced by pw_remote_update_state().
pw_remote_update_state()
void pw_remote_update_state (struct pw_remote * remote, enum pw_remote_state state, const char * fmt, ...)
Update the state of the remote, mostly used by protocols.
References pw_remote_state_as_string().
Referenced by pw_remote_connect(), pw_remote_connect_fd(), and pw_remote_disconnect().