PipeWire: stream.c File Reference
stream.c File Reference
Functions
const char * pw_stream_state_as_string (enum pw_stream_state state)
struct pw_stream * pw_stream_new (struct pw_remote *remote, const char *name, struct pw_properties *props)
enum pw_stream_state pw_stream_get_state (struct pw_stream *stream, const char **error)
const char * pw_stream_get_name (struct pw_stream *stream)
const struct pw_properties * pw_stream_get_properties (struct pw_stream *stream)
void pw_stream_add_listener (struct pw_stream *stream, struct spa_hook *listener, const struct pw_stream_events *events, void *data)
void pw_stream_destroy (struct pw_stream *stream)
bool pw_stream_connect (struct pw_stream *stream, enum pw_direction direction, enum pw_stream_mode mode, const char *port_path, enum pw_stream_flags flags, uint32_t n_possible_formats, const struct spa_format **possible_formats)
uint32_t pw_stream_get_node_id (struct pw_stream *stream)
void pw_stream_finish_format (struct pw_stream *stream, int res, struct spa_param **params, uint32_t n_params)
void pw_stream_disconnect (struct pw_stream *stream)
bool pw_stream_get_time (struct pw_stream *stream, struct pw_time *time)
uint32_t pw_stream_get_empty_buffer (struct pw_stream *stream)
bool pw_stream_recycle_buffer (struct pw_stream *stream, uint32_t id)
struct spa_buffer * pw_stream_peek_buffer (struct pw_stream *stream, uint32_t id)
bool pw_stream_send_buffer (struct pw_stream *stream, uint32_t id)
Function Documentation
pw_stream_add_listener()
void pw_stream_add_listener (struct pw_stream * stream, struct spa_hook * listener, const struct pw_stream_events * events, void * data)
pw_stream_connect()
bool pw_stream_connect (struct pw_stream * stream, enum pw_direction direction, enum pw_stream_mode mode, const char * port_path, enum pw_stream_flags flags, uint32_t n_possible_formats, const struct spa_format ** possible_formats)
References PW_DIRECTION_INPUT.
pw_stream_destroy()
void pw_stream_destroy (struct pw_stream * stream)
References pw_stream_disconnect().
Referenced by pw_remote_destroy().
pw_stream_disconnect()
void pw_stream_disconnect (struct pw_stream * stream)
Referenced by pw_remote_disconnect(), and pw_stream_destroy().
pw_stream_finish_format()
void pw_stream_finish_format (struct pw_stream * stream, int res, struct spa_param ** params, uint32_t n_params)
pw_stream_get_empty_buffer()
uint32_t pw_stream_get_empty_buffer (struct pw_stream * stream)
pw_stream_get_name()
const char* pw_stream_get_name (struct pw_stream * stream)
pw_stream_get_node_id()
uint32_t pw_stream_get_node_id (struct pw_stream * stream)
pw_stream_get_properties()
const struct pw_properties* pw_stream_get_properties (struct pw_stream * stream)
pw_stream_get_state()
enum pw_stream_state pw_stream_get_state (struct pw_stream * stream, const char ** error)
pw_stream_get_time()
bool pw_stream_get_time (struct pw_stream * stream, struct pw_time * time)
References pw_time::now, pw_time::rate, and pw_time::ticks.
pw_stream_new()
struct pw_stream* pw_stream_new (struct pw_remote * remote, const char * name, struct pw_properties * props)
References pw_properties_get(), pw_properties_new(), pw_properties_set(), and PW_STREAM_STATE_UNCONNECTED.
pw_stream_peek_buffer()
struct spa_buffer* pw_stream_peek_buffer (struct pw_stream * stream, uint32_t id)
pw_stream_recycle_buffer()
bool pw_stream_recycle_buffer (struct pw_stream * stream, uint32_t id)
pw_stream_send_buffer()
bool pw_stream_send_buffer (struct pw_stream * stream, uint32_t id)
pw_stream_state_as_string()
const char* pw_stream_state_as_string (enum pw_stream_state state)
References PW_STREAM_STATE_CONFIGURE, PW_STREAM_STATE_CONNECTING, PW_STREAM_STATE_ERROR, PW_STREAM_STATE_PAUSED, PW_STREAM_STATE_READY, PW_STREAM_STATE_STREAMING, and PW_STREAM_STATE_UNCONNECTED.